using BGReportMetrics.API.Data;
using BGReportMetrics.API.Models.DTOs;
using Dapper;
using Microsoft.Data.Sqlite;

namespace BGReportMetrics.API.Services;

public class MetricsService(MglDbContext mglDb, LimsDbContext limsDb, IConfiguration cfg)
{
    // ── Connection helpers ───────────────────────────────────────────────
    // MGL  → Samples, ArchiveReportLog, SamplesAdditionalInfo, ReportUnlocks, AllTestCodes, ClientTestCodes
    // LIMS → LimsReport, LimsOrder, PanelTestCode, LimsReportUnlocks
    private SqliteConnection MglConn()  => new(cfg.GetConnectionString("MglConnection"));
    private SqliteConnection LimsConn() => new(cfg.GetConnectionString("LimsConnection"));

    // ── 1. Reports by test — MGL ─────────────────────────────────────────
    public async Task<List<ReportsByTestDto>> GetReportsByTestAsync(DateTime start, DateTime end)
    {
        using var conn = MglConn();
        var rows = await conn.QueryAsync<ReportsByTestDto>("""
            SELECT s.TestCode, COUNT(*) as Count
            FROM Samples s
            INNER JOIN ArchiveReportLog ar ON s.Id = ar.SamplesId
            WHERE s.FaxedDate BETWEEN @start AND @end
              AND s.BillType <> 'CAN'
            GROUP BY s.TestCode
            ORDER BY s.TestCode
            """, new { start, end });
        return rows.ToList();
    }

    // ── 2a. Auto-generated — MGL (non-PGx) ──────────────────────────────
    public async Task<int> GetAutoGeneratedMglAsync(DateTime start, DateTime end)
    {
        using var conn = MglConn();
        return await conn.ExecuteScalarAsync<int>("""
            SELECT COUNT(*) FROM Samples s
            INNER JOIN SamplesAdditionalInfo sai ON s.Id = sai.SampleId
            WHERE s.FaxedDate BETWEEN @start AND @end
              AND s.OriginalFaxDate IS NULL
              AND sai.WasAutoSignedOut = 1
            """, new { start, end });
    }

    // ── 2b. Auto-generated — LIMS (PGx) ─────────────────────────────────
    public async Task<int> GetAutoGeneratedPgxAsync(DateTime start, DateTime end)
    {
        using var conn = LimsConn();
        return await conn.ExecuteScalarAsync<int>("""
            SELECT COUNT(*) FROM LimsReport
            WHERE ReportedBy = 'PGxAutoSignout'
              AND ReportedDate BETWEEN @start AND @end
            """, new { start, end });
    }

    // ── 3a. Manual reports — MGL (non-PGx) ──────────────────────────────
    public async Task<int> GetManualMglAsync(DateTime start, DateTime end)
    {
        using var conn = MglConn();
        return await conn.ExecuteScalarAsync<int>("""
            SELECT COUNT(*) FROM Samples s
            WHERE s.BillType NOT IN ('CAN','PNL')
              AND s.ManualClose <> 1
              AND (
                s.OriginalFaxDate BETWEEN @start AND @end
                OR (
                  s.FaxedDate BETWEEN @start AND @end
                  AND s.TestCode NOT IN ('60140','60145','61200','64000','64005','24001')
                )
              )
            """, new { start, end });
    }

    // ── 3b. Manual reports — LIMS (PGx) ─────────────────────────────────
    public async Task<int> GetManualPgxAsync(DateTime start, DateTime end)
    {
        using var conn = LimsConn();
        return await conn.ExecuteScalarAsync<int>("""
            SELECT COUNT(*) FROM LimsReport
            WHERE ReportedBy != 'PGxAutoSignout'
              AND ReportedDate BETWEEN @start AND @end
            """, new { start, end });
    }

    // ── 4. Reanalysis requests — MGL ────────────────────────────────────
    public async Task<int> GetReanalysisCountAsync(DateTime start, DateTime end)
    {
        using var conn = MglConn();
        return await conn.ExecuteScalarAsync<int>("""
            SELECT COUNT(*) FROM Samples s
            WHERE s.BillType NOT IN ('CAN','PNL')
              AND s.FaxedDate BETWEEN @start AND @end
              AND s.TestCode IN ('1900','1897')
            """, new { start, end });
    }

    // ── 5. Amended / Corrected ───────────────────────────────────────────
    // MGL  → non-PGx / non-BIO  (Samples + ArchiveReportLog + ReportUnlocks)
    // LIMS → PGx / BIO           (LimsOrder + LimsReport + LimsReportUnlocks)
    public async Task<AmendedCorrectedDto> GetAmendedCorrectedAsync(DateTime start, DateTime end)
    {
        using var mgl  = MglConn();
        using var lims = LimsConn();

        var mglRows = await mgl.QueryAsync<AmendedMglDto>("""
            SELECT s.LabNumber, ru.Reason, ru.ReportUnlockType, COUNT(*) as Count
            FROM Samples s
            INNER JOIN ArchiveReportLog ar ON s.Id = ar.SamplesId
            INNER JOIN ReportUnlocks ru ON s.Id = ru.SampleId
            WHERE s.OriginalFaxDate BETWEEN @start AND @end
              AND s.FaxedDate IS NOT NULL
              AND ru.ReportUnlockType <> 'Clean'
            GROUP BY s.LabNumber, ru.ReportUnlockType, ru.Reason
            ORDER BY s.LabNumber DESC
            """, new { start, end });

        var limsRows = await lims.QueryAsync<AmendedLimsDto>("""
            SELECT O.OldLabNumber as LabNumber, U.ReportUnlockType, U.Reason
            FROM LimsOrder O
            JOIN LimsReport R ON R.OrderId = O.Id
            JOIN LimsReportUnlocks U ON U.ReportId = R.Id
            WHERE U.IsOnReport = 1
              AND R.ReportedDate BETWEEN @start AND @end
            ORDER BY O.OldLabNumber DESC
            """, new { start, end });

        return new AmendedCorrectedDto { Mgl = mglRows.ToList(), Lims = limsRows.ToList() };
    }

    // ── 6. Failed quality — MGL ──────────────────────────────────────────
    public async Task<int> GetFailedQualityAsync(DateTime start, DateTime end)
    {
        using var conn = MglConn();
        return await conn.ExecuteScalarAsync<int>("""
            SELECT SUM(GroupCount) FROM (
              SELECT COUNT(*) as GroupCount
              FROM Samples s
              WHERE s.FaxedDate BETWEEN @start AND @end
                AND s.BillType = 'CAN'
                AND s.ManualClose <> 1
                AND LOWER(CAST(s.Interpretation AS TEXT)) LIKE '%quality%'
            )
            """, new { start, end });
    }

    // ── 7. Cancelled — MGL ──────────────────────────────────────────────
    public async Task<int> GetCancelledCountAsync(DateTime start, DateTime end)
    {
        using var conn = MglConn();
        return await conn.ExecuteScalarAsync<int>("""
            SELECT COUNT(*) FROM Samples s
            WHERE s.BillType = 'CAN'
              AND s.ManualClose <> 1
              AND s.FaxedDate BETWEEN @start AND @end
            """, new { start, end });
    }

    // ── 8. Upgraded orders — MGL ─────────────────────────────────────────
    public async Task<int> GetUpgradedOrdersAsync(DateTime start, DateTime end)
    {
        using var conn = MglConn();
        return await conn.ExecuteScalarAsync<int>("""
            SELECT COUNT(*) FROM Samples s
            INNER JOIN SamplesAdditionalInfo sai ON s.Id = sai.SampleId
            WHERE sai.UpgradedOrder = 1
              AND s.FaxedDate BETWEEN @start AND @end
            """, new { start, end });
    }

    // ── 9. Delayed reports — MGL ─────────────────────────────────────────
    // Uses AllTestCodes (default TAT) and ClientTestCodes (client-override TAT)
    public async Task<List<DelayedReportDto>> GetDelayedReportsAsync(DateTime start, DateTime end)
    {
        using var conn = MglConn();
        var rows = await conn.QueryAsync<DelayedReportDto>("""
            WITH DelayedCases AS (
                SELECT s.Id,
                    CAST(
                        julianday(s.FaxedDate) -
                        julianday(
                            COALESCE(
                                sai.DueDate,
                                datetime(s.TestOrderDate,
                                    '+' || CAST(COALESCE(ctc.TAT, a.TAT) AS TEXT) || ' days')
                            )
                        )
                    AS INTEGER) AS DelayedDays
                FROM Samples s
                LEFT JOIN ClientTestCodes ctc ON s.ClientTestCodeId = ctc.Id
                INNER JOIN AllTestCodes a ON s.TestCode = a.TestCode
                LEFT JOIN SamplesAdditionalInfo sai ON s.Id = sai.SampleId
                INNER JOIN ArchiveReportLog ar ON s.Id = ar.SamplesId
                WHERE s.FaxedDate BETWEEN @start AND @end
                  AND s.TestOrderDate > '2026-01-01'
                  AND s.BillType NOT IN ('CAN', 'PNL')
                  AND s.OriginalFaxDate IS NULL
            )
            SELECT DelayedDays, COUNT(*) AS NumberOfCases
            FROM DelayedCases
            GROUP BY DelayedDays
            HAVING DelayedDays > 0
            ORDER BY DelayedDays DESC
            """, new { start, end });
        return rows.ToList();
    }

    // ── 10. Full summary — parallel across both DBs ──────────────────────
    public async Task<SummaryDto> GetSummaryAsync(DateTime start, DateTime end)
    {
        var t1  = GetReportsByTestAsync(start, end);
        var t2  = GetAutoGeneratedMglAsync(start, end);
        var t3  = GetAutoGeneratedPgxAsync(start, end);
        var t4  = GetManualMglAsync(start, end);
        var t5  = GetManualPgxAsync(start, end);
        var t6  = GetReanalysisCountAsync(start, end);
        var t7  = GetFailedQualityAsync(start, end);
        var t8  = GetCancelledCountAsync(start, end);
        var t9  = GetUpgradedOrdersAsync(start, end);
        var t10 = GetDelayedReportsAsync(start, end);

        await Task.WhenAll(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);

        return new SummaryDto
        {
            ReportsByTest    = await t1,
            AutogeneratedMgl = await t2,
            AutogeneratedPgx = await t3,
            ManualMgl        = await t4,
            ManualPgx        = await t5,
            Reanalysis       = await t6,
            FailedQuality    = await t7,
            Cancelled        = await t8,
            UpgradedOrders   = await t9,
            DelayedReports   = await t10,
        };
    }
}
