namespace BGReportMetrics.API.Models.DTOs;

// Dapper-compatible classes (needs settable properties, not positional records)

public class ReportsByTestDto
{
    public string TestCode { get; set; } = string.Empty;
    public int Count { get; set; }
}

public class CountDto
{
    public int Count { get; set; }
}

public class DualCountDto
{
    public int MglCount { get; set; }
    public int PgxCount { get; set; }
    public int Total => MglCount + PgxCount;
}

public class AmendedMglDto
{
    public string LabNumber { get; set; } = string.Empty;
    public string Reason { get; set; } = string.Empty;
    public string ReportUnlockType { get; set; } = string.Empty;
    public int Count { get; set; }
}

public class AmendedLimsDto
{
    public string LabNumber { get; set; } = string.Empty;
    public string ReportUnlockType { get; set; } = string.Empty;
    public string Reason { get; set; } = string.Empty;
}

public class AmendedCorrectedDto
{
    public List<AmendedMglDto> Mgl { get; set; } = [];
    public List<AmendedLimsDto> Lims { get; set; } = [];
}

public class DelayedReportDto
{
    public int DelayedDays { get; set; }
    public int NumberOfCases { get; set; }
}

public class SummaryDto
{
    public List<ReportsByTestDto> ReportsByTest { get; set; } = [];
    public int AutogeneratedMgl { get; set; }
    public int AutogeneratedPgx { get; set; }
    public int ManualMgl { get; set; }
    public int ManualPgx { get; set; }
    public int Reanalysis { get; set; }
    public int FailedQuality { get; set; }
    public int Cancelled { get; set; }
    public int UpgradedOrders { get; set; }
    public List<DelayedReportDto> DelayedReports { get; set; } = [];
}

public class StaticListDto
{
    public string Name { get; set; } = string.Empty;
    public StaticListDto() { }
    public StaticListDto(string name) { Name = name; }
}
