using BGReportMetrics.API.Services;
using Microsoft.AspNetCore.Mvc;

namespace BGReportMetrics.API.Controllers;

[ApiController]
[Route("api/[controller]")]
public class MetricsController(MetricsService svc) : ControllerBase
{
    private (DateTime start, DateTime end) Parse(string? startDate, string? endDate)
    {
        var s = DateTime.TryParse(startDate, out var sd) ? sd : new DateTime(2026, 3, 1);
        var e = DateTime.TryParse(endDate, out var ed) ? ed : new DateTime(2026, 5, 31);
        return (s, e.Date.AddDays(1).AddTicks(-1)); // inclusive end-of-day
    }

    [HttpGet("summary")]
    public async Task<IActionResult> Summary([FromQuery] string? startDate, [FromQuery] string? endDate)
    {
        var (s, e) = Parse(startDate, endDate);
        return Ok(await svc.GetSummaryAsync(s, e));
    }

    [HttpGet("reports-by-test")]
    public async Task<IActionResult> ReportsByTest([FromQuery] string? startDate, [FromQuery] string? endDate)
    {
        var (s, e) = Parse(startDate, endDate);
        return Ok(await svc.GetReportsByTestAsync(s, e));
    }

    [HttpGet("autogenerated")]
    public async Task<IActionResult> Autogenerated([FromQuery] string? startDate, [FromQuery] string? endDate)
    {
        var (s, e) = Parse(startDate, endDate);
        var mgl = await svc.GetAutoGeneratedMglAsync(s, e);
        var pgx = await svc.GetAutoGeneratedPgxAsync(s, e);
        return Ok(new { mglCount = mgl, pgxCount = pgx, total = mgl + pgx });
    }

    [HttpGet("manual")]
    public async Task<IActionResult> Manual([FromQuery] string? startDate, [FromQuery] string? endDate)
    {
        var (s, e) = Parse(startDate, endDate);
        var mgl = await svc.GetManualMglAsync(s, e);
        var pgx = await svc.GetManualPgxAsync(s, e);
        return Ok(new { mglCount = mgl, pgxCount = pgx, total = mgl + pgx });
    }

    [HttpGet("reanalysis")]
    public async Task<IActionResult> Reanalysis([FromQuery] string? startDate, [FromQuery] string? endDate)
    {
        var (s, e) = Parse(startDate, endDate);
        return Ok(new { count = await svc.GetReanalysisCountAsync(s, e) });
    }

    [HttpGet("amended-corrected")]
    public async Task<IActionResult> AmendedCorrected([FromQuery] string? startDate, [FromQuery] string? endDate)
    {
        var (s, e) = Parse(startDate, endDate);
        return Ok(await svc.GetAmendedCorrectedAsync(s, e));
    }

    [HttpGet("failed-quality")]
    public async Task<IActionResult> FailedQuality([FromQuery] string? startDate, [FromQuery] string? endDate)
    {
        var (s, e) = Parse(startDate, endDate);
        return Ok(new { count = await svc.GetFailedQualityAsync(s, e) });
    }

    [HttpGet("cancelled")]
    public async Task<IActionResult> Cancelled([FromQuery] string? startDate, [FromQuery] string? endDate)
    {
        var (s, e) = Parse(startDate, endDate);
        return Ok(new { count = await svc.GetCancelledCountAsync(s, e) });
    }

    [HttpGet("upgraded-orders")]
    public async Task<IActionResult> UpgradedOrders([FromQuery] string? startDate, [FromQuery] string? endDate)
    {
        var (s, e) = Parse(startDate, endDate);
        return Ok(new { count = await svc.GetUpgradedOrdersAsync(s, e) });
    }

    [HttpGet("delayed-reports")]
    public async Task<IActionResult> DelayedReports([FromQuery] string? startDate, [FromQuery] string? endDate)
    {
        var (s, e) = Parse(startDate, endDate);
        return Ok(await svc.GetDelayedReportsAsync(s, e));
    }
}
